### ISSUE TITLE
Testing phase using HTTP instead of 0MQ doesn't work

### ISSUE THREAD

**Issue by dennismorello** [crowdrec/idomaar#74]
I'm using HTTP as communication protocol between computing environment and orchestrator and I have implemented a HTTP REST server in Python that runs into the computing environment. The problem arises when the testing phase starts: orchestrator is keep waiting for a finish message from recommendation manager (actually the HTTP server itself) and nothing happens until the execution is manually interrupted. Flume's log files contains these exceptions:
* Unable to start SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@365474b4 counterGroup:{ n
ame:null counters:{} } } - Exception follows. **java.lang.NoClassDefFoundError**: Could not initialize class com.yammer.metrics.Metrics
* Unsuccessful attempt to shutdown component: {} due to missing dependencies. Please shutdown the agentor disable this component, or the agent will bein an undefined state. **java.lang.NullPointerException**
* Unable to start SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@31c1fb39 counterGroup:{ name:null counters:{} } } - Exception follows. **java.lang.ExceptionInInitializerError**
* Unsuccessful attempt to shutdown component: {} due to missing dependencies. Please shutdown the agentor disable this component, or the agent will bein an undefined state. **java.lang.NullPointerException**

**Comment by andreas-dai** [comment]
Hi Dennis, regarding the problem, I am not the expert. It looks to me as if a component is missing or the java dependencies are not configured correctly. I guess that Davide or Andras are the experts for this problem. Kind Regards, Andreas

**Comment by dennismorello** [comment]
Thanks Andreas, let's wait for a response from Andras.

**Comment by andras-sereny** [comment]
Hi Dennis, do you have a command line I can run to reproduce the issue?

**Comment by dennismorello** [comment]
You can find all the necessary to reproduce it into the branch **neural-network**

**Comment by andras-sereny** [comment]
How do you start Idomaar?

**Comment by dennismorello** [comment]
Give me a sec, I'm pushing my local changes :)

**Comment by dennismorello** [comment]
Ok I have pushed my changes, you can start Idomaar by launching "idomaar-demo.sh" in the root folder

**Comment by andras-sereny** [comment]
The neural-network branch has some issues atm: gru_recommender.py is missing the web.py dependency and it tries to use the same port 2760 where the old Mahout recommender is listening. If I fix these, there's still some spark-submit error, probably due to the fact that the branch is based on an old Idomaar version. 

As for the original issue, the point here is that in case of an HTTP comp env, our interceptor in Flume did not send an finished message to the orchestartor. I have fixed this on the aws branch, which I think is the most up to date, https://github.com/crowdrec/idomaar/commit/c2655933430715c28de619b594fbd18090fd1816 . I cannot reproduce the Flume errors mentioned above, but in any case, their occurrence cannot depend on the TCP/HTTP computing environment choice. 

@davidemalagoli , could we merge the aws branch to master? Also, idomaar-demo.sh still fails in the eval phase, see #75. who could take a look at it? Thanks, András

**Comment by davidemalagoli** [comment]
merged aws into master
