### ISSUE TITLE
CLEF-NewsREEL evaluation environment error - [datastream] Evaluator: no recommendations received for 60 secs, stopping.

### ISSUE THREAD

**Issue by chgolian** [crowdrec/idomaar#79]
Hello,

I set up evaluation environment for CLEF-NewsREEL Task 2 according to this [tutorial](http://www.clef-newsreel.org/wp-content/uploads/2016/01/TutorialTask2-v03e.pdf)

However, when I run the last command from this tutorial:
<code>
sudo ./idomaar.sh --comp-env-address http://192.168.56.1:8088 --data-source newsreel-test/2014-07-01.data.idomaar_1k.txt --newsreel
</code>
I get this output from datastream:
<code>
[datastream] Evaluator: no recommendations received for 60 secs, stopping.
</code>

Has anybody any idea what could cause this problem?
My computing environment is definitely running.
[Here](https://github.com/crowdrec/idomaar/files/588046/vagrant_up_clef_streams_output.txt) is the result of running <code>vagrant up</code> (computing environment)

And [this](https://github.com/crowdrec/idomaar/files/588048/command_output.txt)
is the output I get when I try to run the evaluation.

Thanks in advance.

**Comment by andreas-dai** [comment]
Hi,

if there are no recommendations received, there might be a problem with the recommender service. In order to check whether the recommender http endpoint is reachable, you could send a test message:
`wget http://192.168.56.1:8088/` 
The recommender should respond with
`Visit <h3><a href="http://www.clef-newsreel.org/">CLEF NewsREEL Challenge</a></h3>`

http-get messages are only used for testing the recommender. In order to test whether the recommender also handles recommendation requests correctly, you could send a recommendation request using something like:
`curl -X POST -d "type=recommendation" -d "body=<AValidJsonLineFromTheLog>" http://192.168.56.1:8088 `

Kind Regards
Andreas

**Comment by andreas-dai** [comment]
![test-the-recommender-service](https://cloud.githubusercontent.com/assets/7116591/20249202/846cc2ac-a9f4-11e6-9e16-86cb23fbe447.png)

**Comment by chgolian** [comment]
Thanks for your quick response.

Yes, this seems to be it.
When running <code>wget http://192.168.56.1:8088/</code>
I get 
<code>--2016-11-13 23:06:36--  http://192.168.56.1:8088/ </code>
<code>Connecting to 192.168.56.1:8088... failed: No route to host.</code>
I guess the problem lies in port forwarding

**Comment by chgolian** [comment]
Thank you for your quick response,

<code>wget</code> seems to be working.
However, when running this
[curl](https://github.com/crowdrec/idomaar/files/588504/example_command.txt)
I get:
<code>unknown MessageType: null</code>

**Comment by andreas-dai** [comment]
It seems that the recommender server is up and running. The response says that there is a problem with the data format of the test message. That is probably because I confused the names of the variables in the post request. I attach a debug message, that works for me (note, that the recommender will respond with an empty recommendation list [] if no items in the requested domain are known - the recommender collects the valid itemIDs in impression messages) 
Finally we now know, that the recommender server is running - but we do not know why no answers are received.
![idommar-http-post-message-test](https://cloud.githubusercontent.com/assets/7116591/20260279/2e166a74-aa59-11e6-8b57-1ee8e64d85a7.png)
[example_command.txt](https://github.com/crowdrec/idomaar/files/588885/example_command.txt)

**Comment by chgolian** [comment]
Could please attach your post request? It seems like you attached mine by mistake.

**Comment by andreas-dai** [comment]
You are right. The json object must be provided as Parameter "properties".
[idomaar-test-message.txt](https://github.com/crowdrec/idomaar/files/590471/idomaar-test-message.txt)

**Comment by chgolian** [comment]
So,

When I run the curl from 'idomaar-test-message.txt' the computing environment responds with empty recommendations list:
<code>{"recs": {"ints": {"3": []}}}</code> (as it should).

However, when I run the idomaar script (with the same computing environment) I still get:
<code>INFO     [datastream] Evaluator: no recommendations received for 60 secs, stopping. </code>
<code>INFO     [datastream] Exception in thread "Thread-6" java.lang.ArithmeticException: / by zero</code>
<code>INFO     [datastream] at eu.crowdrec.idomaar.evaluation.StreamingEvaluator.run(StreamingEvaluator.java:325)</code>

**Comment by andreas-dai** [comment]
A fix to the master branch has been pushed.
(https://github.com/crowdrec/idomaar/commit/71b7f1372e744d2922ce91dc8245e11f9176463d). 
With the fix, we get back some meaningful evaluation results when running 
the CLEF tutorial.
